name: Cronicas Monitor on Supabase

on:
  push:
    paths:
      - 'db/init.sql'

jobs:
  migrate:
    name: Cronicas Monitor
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar cliente PostgreSQL
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: Testar conexão psql
      env:
        PGPASSWORD: ${{ secrets.DB_PASS }}
      run: |
        psql "host=${{ secrets.DB_HOST }} port=${{ secrets.DB_PORT }} user=${{ secrets.DB_USER }} dbname=${{ secrets.DB_NAME }} password=${{ secrets.DB_PASS }} sslmode=require" -c '\conninfo'

    - name: Aplicar init.sql no banco Supabase
      env:
        PGPASSWORD: ${{ secrets.DB_PASS }}
      run: |
        psql -h ${{ secrets.DB_HOST }} \
             -p ${{ secrets.DB_PORT }} \
             -U ${{ secrets.DB_USER }} \
             -d ${{ secrets.DB_NAME }} \
             -f db/init.sql